// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: rpc/accounts/accounts.proto

package accounts_rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DisableCurrencyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *DisableCurrencyReq) Reset() {
	*x = DisableCurrencyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_accounts_accounts_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisableCurrencyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableCurrencyReq) ProtoMessage() {}

func (x *DisableCurrencyReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_accounts_accounts_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableCurrencyReq.ProtoReflect.Descriptor instead.
func (*DisableCurrencyReq) Descriptor() ([]byte, []int) {
	return file_rpc_accounts_accounts_proto_rawDescGZIP(), []int{0}
}

func (x *DisableCurrencyReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type DisableCurrencyResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Can bool `protobuf:"varint,1,opt,name=can,proto3" json:"can,omitempty"`
}

func (x *DisableCurrencyResp) Reset() {
	*x = DisableCurrencyResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_accounts_accounts_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisableCurrencyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableCurrencyResp) ProtoMessage() {}

func (x *DisableCurrencyResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_accounts_accounts_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableCurrencyResp.ProtoReflect.Descriptor instead.
func (*DisableCurrencyResp) Descriptor() ([]byte, []int) {
	return file_rpc_accounts_accounts_proto_rawDescGZIP(), []int{1}
}

func (x *DisableCurrencyResp) GetCan() bool {
	if x != nil {
		return x.Can
	}
	return false
}

type SettingsByNameReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *SettingsByNameReq) Reset() {
	*x = SettingsByNameReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_accounts_accounts_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SettingsByNameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsByNameReq) ProtoMessage() {}

func (x *SettingsByNameReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_accounts_accounts_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingsByNameReq.ProtoReflect.Descriptor instead.
func (*SettingsByNameReq) Descriptor() ([]byte, []int) {
	return file_rpc_accounts_accounts_proto_rawDescGZIP(), []int{2}
}

func (x *SettingsByNameReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SettingsByNameResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SettingsByNameResp) Reset() {
	*x = SettingsByNameResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_accounts_accounts_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SettingsByNameResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsByNameResp) ProtoMessage() {}

func (x *SettingsByNameResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_accounts_accounts_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingsByNameResp.ProtoReflect.Descriptor instead.
func (*SettingsByNameResp) Descriptor() ([]byte, []int) {
	return file_rpc_accounts_accounts_proto_rawDescGZIP(), []int{3}
}

func (x *SettingsByNameResp) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type UserHasCardsOrAccountsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *UserHasCardsOrAccountsReq) Reset() {
	*x = UserHasCardsOrAccountsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_accounts_accounts_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserHasCardsOrAccountsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserHasCardsOrAccountsReq) ProtoMessage() {}

func (x *UserHasCardsOrAccountsReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_accounts_accounts_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserHasCardsOrAccountsReq.ProtoReflect.Descriptor instead.
func (*UserHasCardsOrAccountsReq) Descriptor() ([]byte, []int) {
	return file_rpc_accounts_accounts_proto_rawDescGZIP(), []int{4}
}

func (x *UserHasCardsOrAccountsReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type UserHasCardsOrAccountsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardsExist    bool `protobuf:"varint,1,opt,name=cardsExist,proto3" json:"cardsExist,omitempty"`
	AccountsExist bool `protobuf:"varint,2,opt,name=accountsExist,proto3" json:"accountsExist,omitempty"`
}

func (x *UserHasCardsOrAccountsResp) Reset() {
	*x = UserHasCardsOrAccountsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_accounts_accounts_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserHasCardsOrAccountsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserHasCardsOrAccountsResp) ProtoMessage() {}

func (x *UserHasCardsOrAccountsResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_accounts_accounts_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserHasCardsOrAccountsResp.ProtoReflect.Descriptor instead.
func (*UserHasCardsOrAccountsResp) Descriptor() ([]byte, []int) {
	return file_rpc_accounts_accounts_proto_rawDescGZIP(), []int{5}
}

func (x *UserHasCardsOrAccountsResp) GetCardsExist() bool {
	if x != nil {
		return x.CardsExist
	}
	return false
}

func (x *UserHasCardsOrAccountsResp) GetAccountsExist() bool {
	if x != nil {
		return x.AccountsExist
	}
	return false
}

type GenerateAndSendTansReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *GenerateAndSendTansReq) Reset() {
	*x = GenerateAndSendTansReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_accounts_accounts_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateAndSendTansReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateAndSendTansReq) ProtoMessage() {}

func (x *GenerateAndSendTansReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_accounts_accounts_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateAndSendTansReq.ProtoReflect.Descriptor instead.
func (*GenerateAndSendTansReq) Descriptor() ([]byte, []int) {
	return file_rpc_accounts_accounts_proto_rawDescGZIP(), []int{6}
}

func (x *GenerateAndSendTansReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type GenerateAndSendTansResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GenerateAndSendTansResp) Reset() {
	*x = GenerateAndSendTansResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_accounts_accounts_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateAndSendTansResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateAndSendTansResp) ProtoMessage() {}

func (x *GenerateAndSendTansResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_accounts_accounts_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateAndSendTansResp.ProtoReflect.Descriptor instead.
func (*GenerateAndSendTansResp) Descriptor() ([]byte, []int) {
	return file_rpc_accounts_accounts_proto_rawDescGZIP(), []int{7}
}

type GenerateAccountReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid          string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	CurrencyCode string `protobuf:"bytes,2,opt,name=currencyCode,proto3" json:"currencyCode,omitempty"`
}

func (x *GenerateAccountReq) Reset() {
	*x = GenerateAccountReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_accounts_accounts_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateAccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateAccountReq) ProtoMessage() {}

func (x *GenerateAccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_accounts_accounts_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateAccountReq.ProtoReflect.Descriptor instead.
func (*GenerateAccountReq) Descriptor() ([]byte, []int) {
	return file_rpc_accounts_accounts_proto_rawDescGZIP(), []int{8}
}

func (x *GenerateAccountReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *GenerateAccountReq) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

type GenerateAccountResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Number string `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *GenerateAccountResp) Reset() {
	*x = GenerateAccountResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_accounts_accounts_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateAccountResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateAccountResp) ProtoMessage() {}

func (x *GenerateAccountResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_accounts_accounts_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateAccountResp.ProtoReflect.Descriptor instead.
func (*GenerateAccountResp) Descriptor() ([]byte, []int) {
	return file_rpc_accounts_accounts_proto_rawDescGZIP(), []int{9}
}

func (x *GenerateAccountResp) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GenerateAccountResp) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

var File_rpc_accounts_accounts_proto protoreflect.FileDescriptor

var file_rpc_accounts_accounts_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x72, 0x70, 0x63, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2f, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x76,
	0x65, 0x6c, 0x6d, 0x69, 0x65, 0x2e, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x73, 0x22, 0x28, 0x0a, 0x12, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65,
	0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22,
	0x27, 0x0a, 0x13, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x61, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x03, 0x63, 0x61, 0x6e, 0x22, 0x27, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x73, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x2a, 0x0a, 0x12, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x42, 0x79, 0x4e,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2d, 0x0a,
	0x19, 0x55, 0x73, 0x65, 0x72, 0x48, 0x61, 0x73, 0x43, 0x61, 0x72, 0x64, 0x73, 0x4f, 0x72, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x62, 0x0a, 0x1a,
	0x55, 0x73, 0x65, 0x72, 0x48, 0x61, 0x73, 0x43, 0x61, 0x72, 0x64, 0x73, 0x4f, 0x72, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x61,
	0x72, 0x64, 0x73, 0x45, 0x78, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a,
	0x63, 0x61, 0x72, 0x64, 0x73, 0x45, 0x78, 0x69, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x45, 0x78, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0d, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x45, 0x78, 0x69, 0x73, 0x74,
	0x22, 0x2a, 0x0a, 0x16, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x64, 0x53,
	0x65, 0x6e, 0x64, 0x54, 0x61, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x19, 0x0a, 0x17,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x64, 0x53, 0x65, 0x6e, 0x64, 0x54,
	0x61, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x4a, 0x0a, 0x12, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12,
	0x22, 0x0a, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x43,
	0x6f, 0x64, 0x65, 0x22, 0x3d, 0x0a, 0x13, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x32, 0xd6, 0x04, 0x0a, 0x11, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x50,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x6d, 0x0a, 0x12, 0x43, 0x61, 0x6e, 0x44,
	0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x2a,
	0x2e, 0x76, 0x65, 0x6c, 0x6d, 0x69, 0x65, 0x2e, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x43,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x2b, 0x2e, 0x76, 0x65, 0x6c,
	0x6d, 0x69, 0x65, 0x2e, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x73, 0x2e, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x6a, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x53, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x29, 0x2e, 0x76,
	0x65, 0x6c, 0x6d, 0x69, 0x65, 0x2e, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x42, 0x79,
	0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x2a, 0x2e, 0x76, 0x65, 0x6c, 0x6d, 0x69, 0x65,
	0x2e, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73,
	0x2e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x81, 0x01, 0x0a, 0x18, 0x55, 0x73, 0x65, 0x72, 0x48, 0x61, 0x73, 0x43,
	0x61, 0x72, 0x64, 0x73, 0x4f, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x42, 0x79,
	0x12, 0x31, 0x2e, 0x76, 0x65, 0x6c, 0x6d, 0x69, 0x65, 0x2e, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74,
	0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x48, 0x61,
	0x73, 0x43, 0x61, 0x72, 0x64, 0x73, 0x4f, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x1a, 0x32, 0x2e, 0x76, 0x65, 0x6c, 0x6d, 0x69, 0x65, 0x2e, 0x77, 0x61, 0x6c,
	0x6c, 0x65, 0x74, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x48, 0x61, 0x73, 0x43, 0x61, 0x72, 0x64, 0x73, 0x4f, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x76, 0x0a, 0x13, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x41, 0x6e, 0x64, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x61, 0x6e, 0x73, 0x12, 0x2e,
	0x2e, 0x76, 0x65, 0x6c, 0x6d, 0x69, 0x65, 0x2e, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x41, 0x6e, 0x64, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x61, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x2f,
	0x2e, 0x76, 0x65, 0x6c, 0x6d, 0x69, 0x65, 0x2e, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x41, 0x6e, 0x64, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x61, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x6a, 0x0a, 0x0f, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x2a, 0x2e, 0x76, 0x65, 0x6c, 0x6d, 0x69, 0x65, 0x2e, 0x77, 0x61, 0x6c, 0x6c,
	0x65, 0x74, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x2b,
	0x2e, 0x76, 0x65, 0x6c, 0x6d, 0x69, 0x65, 0x2e, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0a, 0x5a, 0x08, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_accounts_accounts_proto_rawDescOnce sync.Once
	file_rpc_accounts_accounts_proto_rawDescData = file_rpc_accounts_accounts_proto_rawDesc
)

func file_rpc_accounts_accounts_proto_rawDescGZIP() []byte {
	file_rpc_accounts_accounts_proto_rawDescOnce.Do(func() {
		file_rpc_accounts_accounts_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_accounts_accounts_proto_rawDescData)
	})
	return file_rpc_accounts_accounts_proto_rawDescData
}

var file_rpc_accounts_accounts_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_rpc_accounts_accounts_proto_goTypes = []interface{}{
	(*DisableCurrencyReq)(nil),         // 0: velmie.wallet.accounts.DisableCurrencyReq
	(*DisableCurrencyResp)(nil),        // 1: velmie.wallet.accounts.DisableCurrencyResp
	(*SettingsByNameReq)(nil),          // 2: velmie.wallet.accounts.SettingsByNameReq
	(*SettingsByNameResp)(nil),         // 3: velmie.wallet.accounts.SettingsByNameResp
	(*UserHasCardsOrAccountsReq)(nil),  // 4: velmie.wallet.accounts.UserHasCardsOrAccountsReq
	(*UserHasCardsOrAccountsResp)(nil), // 5: velmie.wallet.accounts.UserHasCardsOrAccountsResp
	(*GenerateAndSendTansReq)(nil),     // 6: velmie.wallet.accounts.GenerateAndSendTansReq
	(*GenerateAndSendTansResp)(nil),    // 7: velmie.wallet.accounts.GenerateAndSendTansResp
	(*GenerateAccountReq)(nil),         // 8: velmie.wallet.accounts.GenerateAccountReq
	(*GenerateAccountResp)(nil),        // 9: velmie.wallet.accounts.GenerateAccountResp
}
var file_rpc_accounts_accounts_proto_depIdxs = []int32{
	0, // 0: velmie.wallet.accounts.AccountsProcessor.CanDisableCurrency:input_type -> velmie.wallet.accounts.DisableCurrencyReq
	2, // 1: velmie.wallet.accounts.AccountsProcessor.GetSettingsByName:input_type -> velmie.wallet.accounts.SettingsByNameReq
	4, // 2: velmie.wallet.accounts.AccountsProcessor.UserHasCardsOrAccountsBy:input_type -> velmie.wallet.accounts.UserHasCardsOrAccountsReq
	6, // 3: velmie.wallet.accounts.AccountsProcessor.GenerateAndSendTans:input_type -> velmie.wallet.accounts.GenerateAndSendTansReq
	8, // 4: velmie.wallet.accounts.AccountsProcessor.GenerateAccount:input_type -> velmie.wallet.accounts.GenerateAccountReq
	1, // 5: velmie.wallet.accounts.AccountsProcessor.CanDisableCurrency:output_type -> velmie.wallet.accounts.DisableCurrencyResp
	3, // 6: velmie.wallet.accounts.AccountsProcessor.GetSettingsByName:output_type -> velmie.wallet.accounts.SettingsByNameResp
	5, // 7: velmie.wallet.accounts.AccountsProcessor.UserHasCardsOrAccountsBy:output_type -> velmie.wallet.accounts.UserHasCardsOrAccountsResp
	7, // 8: velmie.wallet.accounts.AccountsProcessor.GenerateAndSendTans:output_type -> velmie.wallet.accounts.GenerateAndSendTansResp
	9, // 9: velmie.wallet.accounts.AccountsProcessor.GenerateAccount:output_type -> velmie.wallet.accounts.GenerateAccountResp
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_accounts_accounts_proto_init() }
func file_rpc_accounts_accounts_proto_init() {
	if File_rpc_accounts_accounts_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_accounts_accounts_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisableCurrencyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_accounts_accounts_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisableCurrencyResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_accounts_accounts_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SettingsByNameReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_accounts_accounts_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SettingsByNameResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_accounts_accounts_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserHasCardsOrAccountsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_accounts_accounts_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserHasCardsOrAccountsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_accounts_accounts_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateAndSendTansReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_accounts_accounts_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateAndSendTansResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_accounts_accounts_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateAccountReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_accounts_accounts_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateAccountResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_accounts_accounts_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_accounts_accounts_proto_goTypes,
		DependencyIndexes: file_rpc_accounts_accounts_proto_depIdxs,
		MessageInfos:      file_rpc_accounts_accounts_proto_msgTypes,
	}.Build()
	File_rpc_accounts_accounts_proto = out.File
	file_rpc_accounts_accounts_proto_rawDesc = nil
	file_rpc_accounts_accounts_proto_goTypes = nil
	file_rpc_accounts_accounts_proto_depIdxs = nil
}
